server:
  port: 9000 #端口
  context-path: /example #项目的url
  tomcat:
    uri-encoding: UTF-8
spring:
  thymeleaf:
    cache: false #关闭缓存，开发时最好关闭
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_example
    username: root
    password: 123456
#jpa:
 #   hibernate:
  #    ddl-auto: update
   # show-sql: true
  http:
    encoding:
    #这个配置用来解决中文乱码问题（基本上默认都是UTF-8）
      force: true
logging:
  level:
    com:
      example:
        example: debug #显示mybatis的sql语句